### ISSUE TITLE
Evaluate kops vs EKS

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/farallon-image#28]
I'm playing with [kops](https://github.com/kubernetes/kops) for managing AWS Kubernetes clusters instead of EKS. I've been frustrated with EKS a while:

1. It uses [AWS VPC CNI](https://github.com/aws/amazon-vpc-cni-k8s) for networking. This is AWS native, but has one major problem for us - pod density! Each pod requires its own [Elastic Network Interface](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-eni.html). There are fairly strong limits on how many ENIs a node can have. For example, an m5.large node can only have 28 pods! That's very low, and wastes a lot of money.
2. Managing worker nodes is actually quite painful, at least compared to GKE. Managed Node Groups don't scale down to 0, and so we can't really use them. You really end up managing them via eksctl - the aws CLI is too hard, and terraform is also pretty unnecessarily complex.
3. It costs 72$ a month. I want a lower base cost.

(1) was the motivating case. (2) makes me feel like I'm already managing a lot of infrastructure intimately - might as well embrace the extra control provided by kops, no? 

Going to test it out, and keep this issue updated

**Comment by yuvipanda** [comment]
AWS is aware of problem (1) and have a [roadmap for pod density fixes](https://github.com/aws/containers-roadmap/issues/398). Realistically, I don't expect that for another 5-6 months at the earliest.

**Comment by yuvipanda** [comment]
My current setup is:

1. t3.medium master, so it's about 30$ a month base cost. I also want the hub pods in there.
2. EFS for home directories, so you only pay for what you use
3. Autoscale to 0, so you only pay for what you use

**Comment by yuvipanda** [comment]
Things I've had to patch so far:

- kube-dns needs to tolerate being on master
- Need to explicitly remove the node-role master from the master nodes, while leaving the taints. Ohterwise, you can't have external load balancer point to it! See https://github.com/kubernetes/enhancements/pull/1144 and https://github.com/kubernetes/kubernetes/issues/65618

**Comment by yuvipanda** [comment]
So https://github.com/kubernetes/enhancements/pull/1144 ended up needing some work. It needed a couple [feature gates](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/) enabled. And thankfully, kops makes this easy.

I now have a cluster working almost the way I want with the following kops config.

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2021-02-13T23:25:11Z"
  name: farallon-2i2c.k8s.local
spec:
  clusterAutoscaler:
    enabled: true
  api:
    loadBalancer:
      class: Classic
      type: Public
  authorization:
    rbac: {}

  dns:
    kubeDNS:
      provider: CoreDNS
  channel: stable
  cloudProvider: aws
  configBase: s3://2i2c-farallon-pangeo-kops/farallon-2i2c.k8s.local
  containerRuntime: docker
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-us-east-2a
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-us-east-2a
      name: a
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
    featureGates:
      LegacyNodeRoleBehavior: "false"
      ServiceNodeExclusion: "false"
  kubeControllerManager:
    featureGates:
      LegacyNodeRoleBehavior: "false"
      ServiceNodeExclusion: "false"
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.19.7
  masterPublicName: api.farallon-2i2c.k8s.local
  networkCIDR: 172.20.0.0/16
  networking:
    calico:
      majorVersion: v3
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: us-east-2a
    type: Public
    zone: us-east-2a
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-02-13T23:25:12Z"
  labels:
    kops.k8s.io/cluster: farallon-2i2c.k8s.local
  name: master-us-east-2a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  machineType: t3.medium
  maxSize: 1
  minSize: 0
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-2a
  role: Master
  subnets:
  - us-east-2a

---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: farallon-2i2c.k8s.local
    hub.jupyter.org/pool-name: notebook-m5-xlarge
  name: notebook-m5-xlarge-2021-02-15
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  cloudLabels:
      k8s.io/cluster-autoscaler/node-template/label/hub.jupyter.org/pool-name: notebook-pool-m5-xlarge
      k8s.io/cluster-autoscaler/node-template/taint/hub.jupyter.org_dedicated: user:NoSchedule
      k8s.io/cluster-autoscaler/node-template/taint/hub.jupyter.org/dedicated: user:NoSchedule
  taints:
   - hub.jupyter.org_dedicated=user:NoSchedule
   - hub.jupyter.org/dedicated=user:NoSchedule
  nodeLabels:
    hub.jupyter.org/pool-name: notebook-m5-xlarge
  machineType: m5.xlarge
  maxSize: 20
  minSize: 0
  role: Node
  subnets:
  - us-east-2a
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: farallon-2i2c.k8s.local
    hub.jupyter.org/pool-name: notebook-m5-2xlarge
  name: notebook-m5-2xlarge-2021-02-15
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  cloudLabels:
      k8s.io/cluster-autoscaler/node-template/label/hub.jupyter.org/pool-name: notebook-pool-m5-2xlarge
      k8s.io/cluster-autoscaler/node-template/taint/hub.jupyter.org_dedicated: user:NoSchedule
      k8s.io/cluster-autoscaler/node-template/taint/hub.jupyter.org/dedicated: user:NoSchedule
  taints:
   - hub.jupyter.org_dedicated=user:NoSchedule
   - hub.jupyter.org/dedicated=user:NoSchedule
  nodeLabels:
    hub.jupyter.org/pool-name: notebook-m5-2xlarge
  machineType: m5.2xlarge
  maxSize: 20
  minSize: 0
  role: Node
  subnets:
  - us-east-2a
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: farallon-2i2c.k8s.local
    hub.jupyter.org/pool-name: dask-worker
  name: dask-worker-2021-02-15
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  cloudLabels:
      k8s.io/cluster-autoscaler/node-template/label/hub.jupyter.org/pool-name: dask-worker
      k8s.io/cluster-autoscaler/node-template/taint/k8s.dask.org_dedicated: worker:NoSchedule
      k8s.io/cluster-autoscaler/node-template/taint/k8s.dask.org/dedicated: worker:NoSchedule
  taints:
   - k8s.dask.org_dedicated=worker:NoSchedule
   - k8s.dask.org/dedicated=worker:NoSchedule
  nodeLabels:
    hub.jupyter.org/pool-name: dask-worker
  machineType: m5.2xlarge
  maxSize: 50
  minSize: 0
  role: Node
  subnets:
  - us-east-2a
```

I have so far absolutely liked this experience much much more than EKS! There is more control than EKS, which actually is a good thing - since EKS is only 'semi-managed', you are often stuck with places where they have made a constraining decision but not provided enough support to make that work easily. Maybe once managed node groups reach feature parity with other cloud providers.

Something else I really really like is that there's one master node that's running t3.medium, and it contains our JupyterHubs too! So the total base cost becomes a little over 30$ a month. With EKS, you've to pay the 72$ a month master fee, and then enough money for a node to run hub infra. And that extra node needs to be much bigger too, due to low pod density.

I still need to do spot instances, and test dask out.
